version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5555:5432
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes: 
      - db:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env 
    links:
      - db
    command: > 
      sh -c "yarn db:push && yarn dev"

volumes:
  db:
    driver: local
