version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build-app:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn dev

  # build-and-push:
  #   executor: docker/docker
  #   steps:
  #     - setup_remote_docker
  #     - checkout
  #     - docker/check
  #     - docker/build:
  #         image: my_repo/orb-test
  #     - docker/push:
  #         digest-path: /tmp/digest.txt
  #         image: my_repo/orb-test
  #     - run:
  #         command: |
  #           echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build:
    jobs:
      - build-app
      - build-and-push:
          requires:
            - build-app
          filters:
            branches:
              only: main
