version: 2.1

orbs:
  node: circleci/node@5.1.1
  docker: circleci/docker@2.4.0

jobs:
  build-app:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn dev

  build-and-push:
    environment:
      DOCKER_IMAGE: pbl6/test
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-pipeline:
    jobs:
      - build-app
      - build-and-push:
          requires:
            - build-app
          filters:
            branches:
              only: main
