version: 2.1

orbs:
  node: circleci/node@5.1.1

jobs:
  build-app:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build

workflows:
  build:
    jobs:
      - build-app
