'use client'

import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Anna speak</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2"></div>
        </div>
      </main>
    </>
  )
}
